schema = 3

[mod]
  [mod."github.com/KarpelesLab/weak"]
    version = "v0.1.1"
    hash = "sha256-VaekSfWKmcdHnfeBM5T4yG0cku3LHS5lDRNyHAloXso="
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.2"
    hash = "sha256-TOlNouGwNdaCddRwABb1qXp0HTMt6+G4uatzfAg3XFc="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.2.1"
    hash = "sha256-hmJediHYMONMEvrRnMs88OXEp4SDt1Pmi8t8eOEk83o="
  [mod."github.com/diamondburned/adaptive"]
    version = "v0.0.2-0.20221227093656-fa139be203a8"
    hash = "sha256-xIerrbYQf6FPbbRd60OnBStIJMl6mg/Qvl+LTmRbyIw="
  [mod."github.com/diamondburned/arikawa/v3"]
    version = "v3.3.6"
    hash = "sha256-zNmLDanbMP/YD17agnV12q2imqmiEDrJbFl7p8RfTsk="
  [mod."github.com/diamondburned/chatkit"]
    version = "v0.0.0-20240614105536-5788b19145bc"
    hash = "sha256-w6q9vDTUmSwAn6RDhPUzY2VIAvgduSbSxGzh46gLFqQ="
  [mod."github.com/diamondburned/gotk4-adwaita/pkg"]
    version = "v0.0.0-20240712143708-824c3ce8a5f4"
    hash = "sha256-7iwswPgG+Q33r70EjWXiWQZUUf3U0GjTcp2swB/2TyU="
  [mod."github.com/diamondburned/gotk4/pkg"]
    version = "v0.3.1-0.20240731063639-b9c04a888a70"
    hash = "sha256-mj4oMN9b8ysyyXAqcvHWdBaSkJIYXXp5Qbqxn57iGl4="
  [mod."github.com/diamondburned/gotkit"]
    version = "v0.0.0-20240731054606-064593800f03"
    hash = "sha256-4luk1IUFRSkqSCEdHJyMz2FVlrVJDDgCd6PDqBimWAE="
  [mod."github.com/diamondburned/ningen/v3"]
    version = "v3.0.1-0.20240704093451-74ff82d4a145"
    hash = "sha256-OeXhNvm2I/ZYURXcGOf+8A9l7XZf4hcY/Feosu6ZVNU="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.11.0"
    hash = "sha256-iXBBgykYu9Dcd+7LMJyRYc3Ry47jmuLGZFW13zU6toU="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/enescakir/emoji"]
    version = "v1.0.0"
    hash = "sha256-fnYYIR2EQG7CfdEdY8Mui2wVTmrcd0KhZD+SZLXT0fY="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
  [mod."github.com/gorilla/schema"]
    version = "v1.4.1"
    hash = "sha256-1sWmntFnTzzy95TtHSJJEUJpEruVBy7eA38vX8kJ85k="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.1"
    hash = "sha256-eHZ/U+eeE5tSgWc1jEDuBwtTRbXKP9fqP9zfW4Zw8T0="
  [mod."github.com/ianlancetaylor/cgosymbolizer"]
    version = "v0.0.0-20240326020559-581a3f7c677f"
    hash = "sha256-MMcTlhWl6YFAbPVq2lmHt6SiuHgh0DNZdHR2nUNwTzY="
  [mod."github.com/leonelquinteros/gotext"]
    version = "v1.6.0"
    hash = "sha256-eNubWY8l65UGKx21n+rISR1jkV8B4+csuB6Zmt4GPug="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.4"
    hash = "sha256-xLaS+fcxmjsoOC3I5IX4jWkmgPVUFJBKEK+jgY5AFa0="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/puzpuzpuz/xsync/v3"]
    version = "v3.1.0"
    hash = "sha256-LX3udTADhVRKqNUjef1cAvf+EjcRnH0DyqQbaSwtWDQ="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.1"
    hash = "sha256-f2VsDI6G+V2w31tSDzbZPi9EI2E7jRV6Aq8yeOorSZY="
  [mod."github.com/twmb/murmur3"]
    version = "v1.1.8"
    hash = "sha256-j5uSr5TfAFeiCWcG3I6WmVrwEuAe57FSHbEQ9tZbixg="
  [mod."github.com/yalue/merged_fs"]
    version = "v1.3.0"
    hash = "sha256-Ww4EEsieMo7UzQYRBFaJNfNiIMPajCPANGABNeHFL0U="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.1"
    hash = "sha256-3EUgwoZRRs2jNBWSbB0DGNmfBvx7CeAgEwyUdaRaeR4="
  [mod."github.com/zalando/go-keyring"]
    version = "v0.2.4"
    hash = "sha256-Qi9GhaL6SbiyTHyPAfiy61rWmrmRAcqZDWyB6+sX8N4="
  [mod."go4.org"]
    version = "v0.0.0-20230225012048-214862532bf5"
    hash = "sha256-8y7krSESdxZfxTzo16EDqmF8USRzGmLPYr3iKuVYzzE="
  [mod."go4.org/unsafe/assume-no-moving-gc"]
    version = "v0.0.0-20231121144256-b99613f794b6"
    hash = "sha256-p0bcawoazS5r49P8Ru0anJ5crNB0+3xGtzZNpCAe3gI="
  [mod."golang.org/x/crypto"]
    version = "v0.22.0"
    hash = "sha256-2+u9nd32+Bi7EEv7QFc12CRTbfV7DApNv+yKIr7+lTw="
  [mod."golang.org/x/image"]
    version = "v0.18.0"
    hash = "sha256-g9N/y4asXG1lctPJ1KEf8XIjeJi/mQ43EXUa8HTj/zQ="
  [mod."golang.org/x/net"]
    version = "v0.24.0"
    hash = "sha256-w1c21ljta5wNIyel9CSIn/crPzwOCRofNKhqmfs4aEQ="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.19.0"
    hash = "sha256-cmuL31TYLJmDm/fDnI2Sn0wB88cpdOHV1+urorsJWx4="
  [mod."golang.org/x/text"]
    version = "v0.16.0"
    hash = "sha256-hMTO45upjEuA4sJzGplJT+La2n3oAfHccfYWZuHcH+8="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."libdb.so/ctxt"]
    version = "v0.0.0-20240229093153-2db38a5d3c12"
    hash = "sha256-mViBj67wYeuD4mQKMP/4gQo9lFNO6J8HZztHw9ZGPlk="
  [mod."libdb.so/go-emoji"]
    version = "v0.0.0-20240508073816-39776eee41ac"
    hash = "sha256-Lsc8gcjZdlh/J95zoHACfE06xv8TojUIoVoCaugvLlY="
